### ISSUE TITLE
Firefox Error message

### ISSUE THREAD

**Issue by RogueCalypso** [KingsOfXur/wherethefuckisxur#13] opened 2018-10-13 18:45 UTC
"The owner of www.wherethefuckisxur.com has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website."

**Comment by soren42** [comment] 2018-10-13 18:46
This is caused by the name on the  SSL certificate not matching the site name as called.

This will hopefully be resolved with the CloudFlare certificate.

**Closed** 2018-10-15 16:15 UTC
